# 05：颜色空间转换
学习如何进行图片的颜色空间转换，视频中追踪特定颜色的物体。图片等可到文末引用处下载。

# 目标
* 颜色空间转换，如 BGR↔Gray，BGR↔HSV 等
* 追踪视频中特定颜色的物体
* OpenCV 函数：cv2.cvtColor(), cv2.inRange()

In [1]:
import cv2
img=cv2.imread('./imgs/lena.png')

In [2]:
img_gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.imshow('img',img)
cv2.imshow('gray',img_gray)
cv2.waitKey(0)

-1

cv2.cvtColor()用来进行颜色模型转换，参数 1 是要转换的图片，参数 2 是转换模式， COLOR_BGR2GRAY表示 BGR→Gray，可用下面的代码显示所有的转换模式：

In [3]:
flags = [i for i in dir(cv2) if i.startswith('COLOR_')]
print(flags)


['COLOR_BAYER_BG2BGR', 'COLOR_BAYER_BG2BGRA', 'COLOR_BAYER_BG2BGR_EA', 'COLOR_BAYER_BG2BGR_VNG', 'COLOR_BAYER_BG2GRAY', 'COLOR_BAYER_BG2RGB', 'COLOR_BAYER_BG2RGBA', 'COLOR_BAYER_BG2RGB_EA', 'COLOR_BAYER_BG2RGB_VNG', 'COLOR_BAYER_BGGR2BGR', 'COLOR_BAYER_BGGR2BGRA', 'COLOR_BAYER_BGGR2BGR_EA', 'COLOR_BAYER_BGGR2BGR_VNG', 'COLOR_BAYER_BGGR2GRAY', 'COLOR_BAYER_BGGR2RGB', 'COLOR_BAYER_BGGR2RGBA', 'COLOR_BAYER_BGGR2RGB_EA', 'COLOR_BAYER_BGGR2RGB_VNG', 'COLOR_BAYER_GB2BGR', 'COLOR_BAYER_GB2BGRA', 'COLOR_BAYER_GB2BGR_EA', 'COLOR_BAYER_GB2BGR_VNG', 'COLOR_BAYER_GB2GRAY', 'COLOR_BAYER_GB2RGB', 'COLOR_BAYER_GB2RGBA', 'COLOR_BAYER_GB2RGB_EA', 'COLOR_BAYER_GB2RGB_VNG', 'COLOR_BAYER_GBRG2BGR', 'COLOR_BAYER_GBRG2BGRA', 'COLOR_BAYER_GBRG2BGR_EA', 'COLOR_BAYER_GBRG2BGR_VNG', 'COLOR_BAYER_GBRG2GRAY', 'COLOR_BAYER_GBRG2RGB', 'COLOR_BAYER_GBRG2RGBA', 'COLOR_BAYER_GBRG2RGB_EA', 'COLOR_BAYER_GBRG2RGB_VNG', 'COLOR_BAYER_GR2BGR', 'COLOR_BAYER_GR2BGRA', 'COLOR_BAYER_GR2BGR_EA', 'COLOR_BAYER_GR2BGR_VNG', 'COLOR_

经验之谈：颜色转换其实是数学运算，如灰度化最常用的是：gray=R * 0.299+G * 0.587+B * 0.114。

# 视频中特定颜色物体追踪
HSV是一个常用于颜色识别的模型，相比 BGR 更易区分颜色，转换模式用COLOR_BGR2HSV表示。

经验之谈：OpenCV 中色调 H 范围为[0,179]，饱和度 S 是[0,255]，明度 V 是[0,255]。虽然 H 的理论数值是 0°~360°，但 8 位图像像素点的最大值是 255，所以 OpenCV 中除以了 2，某些软件可能使用不同的尺度表示，所以同其他软件混用时，记得归一化。

现在，我们实现一个使用 HSV 来只显示视频中蓝色物体的例子，步骤如下：

1. 捕获视频中的一帧
2. 从 BGR 转换到 HSV
3. 提取蓝色范围的物体
4. 只显示蓝色物体

In [8]:
import numpy as np

capture =cv2.VideoCapture(0)

lower_blue=np.array([110,110,110])
upper_blue=np.array([130,255,255])

while(True):
  ret,frame=capture.read()
  hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
  mask=cv2.inRange(hsv,lower_blue,upper_blue)
  res=cv2.bitwise_and(frame,frame,mask=mask)

  cv2.imshow('frame',frame)
  cv2.imshow('mask',mask)
  cv2.imshow('res',res)

  if cv2.waitKey(1)==ord('q'):
    cv2.destroyAllWindows()
    break



其中，bitwise_and()函数暂时不用管，后面会讲到。那蓝色的 HSV 值的上下限 lower 和 upper 范围是怎么得到的呢？其实很简单，我们先把标准蓝色的 BGR 值用cvtColor()转换下：

In [6]:
blue=np.uint8([[[255,0,0]]])
hsv_blue=cv2.cvtColor(blue,cv2.COLOR_BGR2HSV)
print(hsv_blue)

[[[120 255 255]]]


In [9]:
red=np.uint8([[[0,255,0]]])
hsv_red=cv2.cvtColor(red,cv2.COLOR_BGR2HSV)
print(hsv_red)
green=np.uint8([[[0,0,255]]])
hsv_green=cv2.cvtColor(green,cv2.COLOR_BGR2HSV)
print(hsv_green)

[[[ 60 255 255]]]
[[[  0 255 255]]]


# 小结
* cv2.cvtColor()函数用来进行颜色空间转换，常用 BGR↔Gray，BGR↔HSV。
* HSV 颜色模型常用于颜色识别。要想知道某种颜色在 HSV 下的值，可以将它的 BGR 值用cvtColor()转换得到。

# 练习
尝试在视频中同时提取红色、蓝色、绿色的物体。

In [ ]:
import numpy as np

capture =cv2.VideoCapture(0)

lower=np.array([0,110,110])
upper=np.array([130,255,255])
while(True):
  ret,frame=capture.read()
  hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
  mask=cv2.inRange(hsv,lower,upper)
  res=cv2.bitwise_and(frame,frame,mask=mask)

  cv2.imshow('frame',frame)
  cv2.imshow('mask',mask)
  cv2.imshow('res',res)

  if cv2.waitKey(1)==ord('q'):
    cv2.destroyAllWindows()
    break

In [13]:
import numpy as np
import cv2

capture = cv2.VideoCapture(0)

# 定义红色、蓝色和绿色的颜色范围
lower_red = np.array([0, 100, 100])
upper_red = np.array([10, 255, 255])

lower_blue = np.array([110, 50, 50])
upper_blue = np.array([130, 255, 255])

lower_green = np.array([40, 40, 40])
upper_green = np.array([80, 255, 255])

while True:
    ret, frame = capture.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # 创建红色、蓝色和绿色的掩码
    red_mask = cv2.inRange(hsv, lower_red, upper_red)
    blue_mask = cv2.inRange(hsv, lower_blue, upper_blue)
    green_mask = cv2.inRange(hsv, lower_green, upper_green)

    # 使用掩码提取红色、蓝色和绿色的物体
    red_res = cv2.bitwise_and(frame, frame, mask=red_mask)
    blue_res = cv2.bitwise_and(frame, frame, mask=blue_mask)
    green_res = cv2.bitwise_and(frame, frame, mask=green_mask)

    # 合并结果
    result = cv2.add(red_res, cv2.add(blue_res, green_res))

    cv2.imshow('frame', frame)
    # cv2.imshow('Red Objects', red_res)
    # cv2.imshow('Blue Objects', blue_res)
    # cv2.imshow('Green Objects', green_res)
    cv2.imshow('Result', result)

    if cv2.waitKey(1) == ord('q'):
        cv2.destroyAllWindows()
        break


: 